resources:
  - name: my-api
    type: git
    source:
      uri: git@github.com:jadekler/git-concourse-talk.git
      branch: master

  - name: my-ui
    type: git
    source:
      uri: git@github.com:jadekler/git-concourse-talk.git
      branch: master

jobs:
  - name: api-slow-unit-tests
    plan:
      - get: my-api
        trigger: true
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-api

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact

  - name: api-fast-unit-tests
    plan:
      - get: my-api
        trigger: true
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-api

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact

  - name: api-acceptance-tests
    plan:
      - get: my-api
        trigger: true
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-api

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact

  - name: ui-jslint
    plan:
      - get: my-ui
        trigger: true
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-ui

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact

  - name: ui-slow-unit-tests
    plan:
      - get: my-ui
        trigger: true
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-ui

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact

  - name: ui-fast-unit-tests
    plan:
      - get: my-ui
        trigger: true
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-ui

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact

  - name: ui-acceptance-tests
    plan:
      - get: my-ui
        trigger: true
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-ui

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact



  - name: integration-tests
    plan:
      - get: my-api
        trigger: true
        passed: [api-slow-unit-tests, api-fast-unit-tests, api-acceptance-tests]
      - get: my-ui
        trigger: true
        passed: [ui-jslint, ui-slow-unit-tests, ui-fast-unit-tests, ui-acceptance-tests]
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-api
          - name: my-ui

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact


  - name: deploy-to-acceptance
    plan:
      - get: my-api
        trigger: true
        passed: [integration-tests]
      - get: my-ui
        trigger: true
        passed: [integration-tests]
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-api
          - name: my-ui

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact


  - name: deploy-to-qa-environment
    plan:
      - get: my-api
        trigger: true
        passed: [integration-tests]
      - get: my-ui
        trigger: true
        passed: [integration-tests]
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-api
          - name: my-ui

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact

  - name: deploy-to-prod
    plan:
      - get: my-api
        passed: [integration-tests]
      - get: my-ui
        passed: [integration-tests]
      - task: run-tests
        config:
          platform: linux

          inputs:
          - name: my-api
          - name: my-ui

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'
          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact