resources:
  - name: my-api
    type: git
    source:
      uri: git@github.com:my-org/my-api.git
      branch: master

  - name: my-ui
    type: git
    source:
      uri: git@github.com:my-org/my-ui.git
      branch: master

jobs:
  - name: ui-unit-tests
    plan:
      - get: my-ui
      - task: unit
        file: controller/ui/unit-test.yml

  - name: ui-integration-tests
    plan:
      - get: my-ui
      - task: integration
        file: controller/ui/integration-test.yml

  - name: api-unit-tests
    plan:
      - get: my-api
      - task: unit
        file: controller/api/unit-test.yml

  - name: api-integration-tests
    plan:
      - get: my-api
      - task: integration
        file: controller/api/integration-test.yml

  - name: end-to-end
    plan:
      - aggregate:
        - get: my-ui
          passed: [ui-integration-tests, ui-unit-tests]
        - get: my-api
          passed: [api-integration-tests, api-unit-tests]
      - task: end-to-end
        file: end-to-end/task.yml

  - name: deploy
    plan:
      - aggregate:
        - get: my-ui
          passed: [end-to-end]
        - get: my-api
          passed: [end-to-end]
      - task: deploy-ui
        file: deploy/ui.yml
      - task: deploy-api
        file: deploy/api.yml