resources:
  - name: my-api
    type: git
    source:
      uri: git@github.com:jadekler/git-concourse-talk.git
      branch: master

jobs:
  - name: unit-tests
    plan:
      - get: my-api
      - task: unit
        config:
          platform: linux

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'

          params:
            SOME_PARAM: some-default-value

          inputs:
          - name: some-input
          - name: some-input-with-custom-path
            path: some/custom/path

          outputs:
          - name: some-output

          run:
            path: sh
            args:
            - -exc
            - |
              whoami
              env
              go version
              find .
              touch some-output/my-built-artifact