resources:
  - name: my-api
    type: git
    source:
      uri: git@github.com:jadekler/git-concourse-talk.git
      branch: master

jobs:
  - name: unit-tests
    plan:
      - get: my-api
      - task: unit
        config:
          platform: linux

          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: '1.6'

          run:
            path: sh
            args:
            - -exc
            - |
              cd /path/to/code
              ginkgo
              rspec
              gradle test
              # whatever
